name: CICD

on:
  push:
    branches:
      - master
      - feature/*
      - develop
  pull_request:
    branches:
      - master
      - feature/*
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
          go mod download

      - name: Run build
        run: go build ./pkg/client

      - name: Run vet & lint
        run: |
          find . -type f -name "*.go" -printf %h\\n | uniq | xargs go vet
          find . -type f -name "*.go" -printf %h\\n | uniq | xargs golint

      - name: Run testing
        run: go test ./test -v
